# Generated by Neurodocker and Reproenv.

FROM mambaorg/micromamba:0.24-jammy

COPY --chown=$MAMBA_USER:$MAMBA_USER env.yml /tmp/env.yml
COPY --chown=$MAMBA_USER:$MAMBA_USER pyproject.toml src /tmp/phantomdb/
 
# need to install python first for fsl installer (env handled by some python packages)
# # (otherwise python will not be found)
ENV MAMBA_DOCKERFILE_ACTIVATE=1 
RUN micromamba install --name base --yes --file /tmp/env.yml  \
    && pip install --no-deps /tmp/phantomdb/ \
    && rm -rf /tmp/phantomdb /tmp/env.yml \
    && micromamba clean --yes --all

ENTRYPOINT ["/usr/local/bin/_entrypoint.sh", "/opt/conda/bin/phantomdb"]

